"use client";

import { Download, RotateCcw, Settings, Upload } from "lucide-react";
import { useRef, useState } from "react";
import { useApp } from "@/lib/store";
import { PageHead } from "@/components/ui";
import { AccountCard } from "@/components/account-card";

export default function SettingsPage(){
  const {data,updateSettings,exportData,importData,resetData}=useApp();const file=useRef<HTMLInputElement>(null);const [message,setMessage]=useState("");
  const updateJarvis=(patch:Partial<typeof data.settings.jarvis>)=>updateSettings({jarvis:{...data.settings.jarvis,...patch}});
  const download=()=>{const blob=new Blob([exportData()],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`makerpath-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);setMessage("Backup esportato.")};
  const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const selected=e.target.files?.[0];if(!selected)return;try{importData(JSON.parse(await selected.text()) as unknown);setMessage("Backup importato correttamente.");}catch(error){setMessage(error instanceof Error?error.message:"Importazione non riuscita.");}e.target.value=""};
  return <><PageHead eyebrow="Preferenze" title="Impostazioni" description="Personalizza il ritmo, l’esperienza e la gestione dei tuoi dati."/>
    {message&&<div className="toast" onAnimationEnd={()=>window.setTimeout(()=>setMessage(""),2500)}>{message}</div>}
    <AccountCard />
    <section className="card section"><p className="eyebrow">Obiettivi</p><div className="settings-row"><div><h3 style={{marginBottom:4}}>Ore settimanali</h3><p className="row-meta">Il tuo target di concentrazione.</p></div><input aria-label="Ore settimanali" className="field" style={{width:80}} min="1" max="80" type="number" value={data.settings.weeklyGoal} onChange={e=>updateSettings({weeklyGoal:Number(e.target.value)})}/></div>
      <div className="settings-row"><div><h3 style={{marginBottom:4}}>Giorni previsti</h3><p className="row-meta">Scegli quando vuoi studiare.</p></div><div className="actions">{["L","M","M","G","V","S","D"].map((day,i)=>{const value=i+1===7?0:i+1;const active=data.settings.studyDays.includes(value);return <button aria-label={`Giorno ${i+1}`} key={i} className={`check ${active?"done":""}`} onClick={()=>updateSettings({studyDays:active?data.settings.studyDays.filter(d=>d!==value):[...data.settings.studyDays,value]})}>{day}</button>})}</div></div>
    </section>
    <section className="card section"><p className="eyebrow">Esperienza</p><div className="settings-row"><div><h3 style={{marginBottom:4}}>Tema chiaro</h3><p className="row-meta">Alterna l’aspetto dell’interfaccia.</p></div><button className={`switch ${data.settings.theme==="light"?"on":""}`} aria-label="Cambia tema" onClick={()=>updateSettings({theme:data.settings.theme==="dark"?"light":"dark"})}/></div>
      <div className="settings-row"><div><h3 style={{marginBottom:4}}>Riduci animazioni</h3><p className="row-meta">Limita movimento e transizioni.</p></div><button className={`switch ${data.settings.reduceMotion?"on":""}`} aria-label="Riduci animazioni" onClick={()=>updateSettings({reduceMotion:!data.settings.reduceMotion})}/></div>
    </section>
    <section className="card section"><p className="eyebrow">Jarvis</p>
      <div className="settings-row"><div><h3 style={{marginBottom:4}}>Risposte vocali</h3><p className="row-meta">Voce inglese maschile di sistema; i comandi restano in italiano.</p></div><button className={`switch ${data.settings.jarvis.voiceResponses?"on":""}`} aria-label="Risposte vocali Jarvis" aria-pressed={data.settings.jarvis.voiceResponses} onClick={()=>updateJarvis({voiceResponses:!data.settings.jarvis.voiceResponses})}/></div>
      <div className="settings-row"><div><h3 style={{marginBottom:4}}>Suoni di sistema</h3><p className="row-meta">Feedback discreti per avvio, ascolto ed esito.</p></div><button className={`switch ${data.settings.jarvis.sounds?"on":""}`} aria-label="Suoni Jarvis" aria-pressed={data.settings.jarvis.sounds} onClick={()=>updateJarvis({sounds:!data.settings.jarvis.sounds})}/></div>
      <div className="settings-row"><div><h3 style={{marginBottom:4}}>Animazioni Jarvis</h3><p className="row-meta">Orb, particelle e pulsazioni del Command Center.</p></div><button className={`switch ${data.settings.jarvis.animations?"on":""}`} aria-label="Animazioni Jarvis" aria-pressed={data.settings.jarvis.animations} onClick={()=>updateJarvis({animations:!data.settings.jarvis.animations})}/></div>
      <div className="settings-row"><label htmlFor="jarvis-wake"><h3 style={{marginBottom:4}}>Frase di attivazione</h3><p className="row-meta">Viene riconosciuta in italiano.</p></label><input id="jarvis-wake" className="field" style={{width:170}} value={data.settings.jarvis.wakePhrase} maxLength={32} onChange={e=>updateJarvis({wakePhrase:e.target.value})}/></div>
      <div className="settings-row"><label htmlFor="jarvis-rate"><h3 style={{marginBottom:4}}>Velocità voce</h3><p className="row-meta">{data.settings.jarvis.voiceRate.toFixed(2)}×</p></label><input id="jarvis-rate" aria-label="Velocità voce Jarvis" type="range" min=".7" max="1.25" step=".05" value={data.settings.jarvis.voiceRate} onChange={e=>updateJarvis({voiceRate:Number(e.target.value)})}/></div>
      <div className="settings-row"><label htmlFor="jarvis-volume"><h3 style={{marginBottom:4}}>Volume voce</h3><p className="row-meta">{Math.round(data.settings.jarvis.voiceVolume*100)}%</p></label><input id="jarvis-volume" aria-label="Volume voce Jarvis" type="range" min="0" max="1" step=".05" value={data.settings.jarvis.voiceVolume} onChange={e=>updateJarvis({voiceVolume:Number(e.target.value)})}/></div>
    </section>
    <section className="card section"><p className="eyebrow">Dati & privacy</p><p className="muted" style={{fontSize:13}}>Una copia resta sul dispositivo; quando accedi viene sincronizzata in modo protetto. Puoi comunque esportare un backup indipendente.</p><div className="actions" style={{marginTop:18}}><button className="btn" onClick={download}><Download size={16}/>Esporta JSON</button><button className="btn" onClick={()=>file.current?.click()}><Upload size={16}/>Importa JSON</button><input hidden ref={file} type="file" accept="application/json" onChange={upload}/><button className="btn danger" onClick={()=>{if(confirm("Ripristinare tutti i dati demo? I dati attuali saranno eliminati.")){resetData();setMessage("Dati demo ripristinati.");}}}><RotateCcw size={16}/>Ripristina demo</button></div></section>
    <footer style={{textAlign:"center",padding:"35px 0",color:"var(--muted)",fontSize:12}}><Settings size={18}/><p style={{margin:"8px 0"}}>MakerPath MVP · schema dati v{data.version}</p><span>Build small. Learn deeply.</span></footer>
  </>;
}
